package com.relative.QuskyOro.ObjetosNegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CalculadoraQuskiResponseGarantias implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "CalculadoraQuskiResultGarantias")
	private com.relative.QuskyOro.ObjetosNegocio.CalculadoraQuskiResultGarantias calculadoraQuskiResultGarantias;

	public CalculadoraQuskiResponseGarantias() {
	}

	public com.relative.QuskyOro.ObjetosNegocio.CalculadoraQuskiResultGarantias getCalculadoraQuskiResultGarantias() {
		return this.calculadoraQuskiResultGarantias;
	}

	public void setCalculadoraQuskiResultGarantias(
			com.relative.QuskyOro.ObjetosNegocio.CalculadoraQuskiResultGarantias calculadoraQuskiResultGarantias) {
		this.calculadoraQuskiResultGarantias = calculadoraQuskiResultGarantias;
	}

	public CalculadoraQuskiResponseGarantias(
			com.relative.QuskyOro.ObjetosNegocio.CalculadoraQuskiResultGarantias calculadoraQuskiResultGarantias) {
		this.calculadoraQuskiResultGarantias = calculadoraQuskiResultGarantias;
	}

}