package com.relative.QuskyOro.ObjetosNegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Carga implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("XmlGarantias")
	private com.relative.QuskyOro.ObjetosNegocio.XmlGarantias XmlGarantias;

	@org.kie.api.definition.type.Label("XmlParametrosRiesgo")
	private com.relative.QuskyOro.ObjetosNegocio.XmlParametrosRiesgo XmlParametrosRiesgo;

	@org.kie.api.definition.type.Label("XmlDescuentosNuevaOperacion")
	private com.relative.QuskyOro.ObjetosNegocio.XmlDescuentosNuevaOperacion XmlDescuentosNuevaOperacion;

	@org.kie.api.definition.type.Label("XmlVariablesInternas")
	private com.relative.QuskyOro.ObjetosNegocio.XmlVariablesInternas XmlVariablesInternas;

	public Carga() {
	}

	public com.relative.QuskyOro.ObjetosNegocio.XmlGarantias getXmlGarantias() {
		return this.XmlGarantias;
	}

	public void setXmlGarantias(
			com.relative.QuskyOro.ObjetosNegocio.XmlGarantias XmlGarantias) {
		this.XmlGarantias = XmlGarantias;
	}

	public com.relative.QuskyOro.ObjetosNegocio.XmlParametrosRiesgo getXmlParametrosRiesgo() {
		return this.XmlParametrosRiesgo;
	}

	public void setXmlParametrosRiesgo(
			com.relative.QuskyOro.ObjetosNegocio.XmlParametrosRiesgo XmlParametrosRiesgo) {
		this.XmlParametrosRiesgo = XmlParametrosRiesgo;
	}

	public com.relative.QuskyOro.ObjetosNegocio.XmlDescuentosNuevaOperacion getXmlDescuentosNuevaOperacion() {
		return this.XmlDescuentosNuevaOperacion;
	}

	public void setXmlDescuentosNuevaOperacion(
			com.relative.QuskyOro.ObjetosNegocio.XmlDescuentosNuevaOperacion XmlDescuentosNuevaOperacion) {
		this.XmlDescuentosNuevaOperacion = XmlDescuentosNuevaOperacion;
	}

	public com.relative.QuskyOro.ObjetosNegocio.XmlVariablesInternas getXmlVariablesInternas() {
		return this.XmlVariablesInternas;
	}

	public void setXmlVariablesInternas(
			com.relative.QuskyOro.ObjetosNegocio.XmlVariablesInternas XmlVariablesInternas) {
		this.XmlVariablesInternas = XmlVariablesInternas;
	}

	public Carga(
			com.relative.QuskyOro.ObjetosNegocio.XmlGarantias XmlGarantias,
			com.relative.QuskyOro.ObjetosNegocio.XmlParametrosRiesgo XmlParametrosRiesgo,
			com.relative.QuskyOro.ObjetosNegocio.XmlDescuentosNuevaOperacion XmlDescuentosNuevaOperacion,
			com.relative.QuskyOro.ObjetosNegocio.XmlVariablesInternas XmlVariablesInternas) {
		this.XmlGarantias = XmlGarantias;
		this.XmlParametrosRiesgo = XmlParametrosRiesgo;
		this.XmlDescuentosNuevaOperacion = XmlDescuentosNuevaOperacion;
		this.XmlVariablesInternas = XmlVariablesInternas;
	}

}