package com.relative.QuskyOro.ObjetosNegocio;

import java.lang.Object;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Garantia extends Object implements java.io.Serializable {

	static final long serialVersionUID = 1L;
	@org.kie.api.definition.type.Label("TipoJoya")
	String TipoJoya;
	@org.kie.api.definition.type.Label("Descripcion")
	String Descripcion;
	@org.kie.api.definition.type.Label("EstadoJoya")
	String EstadoJoya;
	@org.kie.api.definition.type.Label("TipoOroKilataje")
	String TipoOroKilataje;
	@org.kie.api.definition.type.Label("PesoGr")
	Double PesoGr;
	@org.kie.api.definition.type.Label("TienePiedras")
	String TienePiedras;
	@org.kie.api.definition.type.Label("DetallePiedras")
	String DetallePiedras;
	@org.kie.api.definition.type.Label("DescuentoPesoPiedras")
	Double DescuentoPesoPiedras;
	@org.kie.api.definition.type.Label("PesoNeto")
	Double PesoNeto;
	@org.kie.api.definition.type.Label("ValorAplicableCredito")
	Double ValorAplicableCredito;
	@org.kie.api.definition.type.Label("ValorRealizacion")
	Double ValorRealizacion;
	@org.kie.api.definition.type.Label("NumeroPiezas")
	int NumeroPiezas;
	@org.kie.api.definition.type.Label("DescuentoSuelda")
	Double DescuentoSuelda;

	@org.kie.api.definition.type.Label(value = "ValorOro")
	private java.lang.Double valorOro;
	@org.kie.api.definition.type.Label(value = "ValorAvaluo")
	private java.lang.Double valorAvaluo;

	public Garantia() {
	}

	// Getter Methods

	public String getTipoJoya() {
		return TipoJoya;
	}

	public String getDescripcion() {
		return Descripcion;
	}

	public String getEstadoJoya() {
		return EstadoJoya;
	}

	public String getTipoOroKilataje() {
		return TipoOroKilataje;
	}

	public Double getPesoGr() {
		return PesoGr;
	}

	public String getDetallePiedras() {
		return DetallePiedras;
	}

	public Double getDescuentoPesoPiedras() {
		return DescuentoPesoPiedras;
	}

	public Double getPesoNeto() {
		return PesoNeto;
	}

	public Double getValorAplicableCredito() {
		return ValorAplicableCredito;
	}

	public Double getValorRealizacion() {
		return ValorRealizacion;
	}

	public int getNumeroPiezas() {
		return NumeroPiezas;
	}

	public Double getDescuentoSuelda() {
		return DescuentoSuelda;
	}

	// Setter Methods

	public void setTipoJoya(String TipoJoya) {
		this.TipoJoya = TipoJoya;
	}

	public void setDescripcion(String Descripcion) {
		this.Descripcion = Descripcion;
	}

	public void setEstadoJoya(String EstadoJoya) {
		this.EstadoJoya = EstadoJoya;
	}
	public void setTipoOroKilataje(String TipoOroKilataje) {
		this.TipoOroKilataje = TipoOroKilataje;
	}

	public void setPesoGr(Double PesoGr) {
		this.PesoGr = PesoGr;
	}

	public void setDetallePiedras(String DetallePiedras) {
		this.DetallePiedras = DetallePiedras;
	}

	public void setDescuentoPesoPiedras(Double DescuentoPesoPiedras) {
		this.DescuentoPesoPiedras = DescuentoPesoPiedras;
	}

	public void setPesoNeto(Double PesoNeto) {
		this.PesoNeto = PesoNeto;
	}

	public void setValorAplicableCredito(Double ValorAplicableCredito) {
		this.ValorAplicableCredito = ValorAplicableCredito;
	}

	public void setValorRealizacion(Double ValorRealizacion) {
		this.ValorRealizacion = ValorRealizacion;
	}

	public void setNumeroPiezas(int NumeroPiezas) {
		this.NumeroPiezas = NumeroPiezas;
	}

	public void setDescuentoSuelda(Double DescuentoSuelda) {
		this.DescuentoSuelda = DescuentoSuelda;
	}

	public java.lang.String getTienePiedras() {
		return this.TienePiedras;
	}

	public void setTienePiedras(java.lang.String TienePiedras) {
		this.TienePiedras = TienePiedras;
	}

	public java.lang.Double getValorOro() {
		return this.valorOro;
	}

	public void setValorOro(java.lang.Double valorOro) {
		this.valorOro = valorOro;
	}

	public java.lang.Double getValorAvaluo() {
		return this.valorAvaluo;
	}

	public void setValorAvaluo(java.lang.Double valorAvaluo) {
		this.valorAvaluo = valorAvaluo;
	}

	public Garantia(java.lang.String TipoJoya, java.lang.String Descripcion,
			java.lang.String EstadoJoya, java.lang.String TipoOroKilataje,
			java.lang.Double PesoGr, java.lang.String TienePiedras,
			java.lang.String DetallePiedras,
			java.lang.Double DescuentoPesoPiedras, java.lang.Double PesoNeto,
			java.lang.Double ValorAplicableCredito,
			java.lang.Double ValorRealizacion, int NumeroPiezas,
			java.lang.Double DescuentoSuelda, java.lang.Double valorOro,
			java.lang.Double valorAvaluo) {
		this.TipoJoya = TipoJoya;
		this.Descripcion = Descripcion;
		this.EstadoJoya = EstadoJoya;
		this.TipoOroKilataje = TipoOroKilataje;
		this.PesoGr = PesoGr;
		this.TienePiedras = TienePiedras;
		this.DetallePiedras = DetallePiedras;
		this.DescuentoPesoPiedras = DescuentoPesoPiedras;
		this.PesoNeto = PesoNeto;
		this.ValorAplicableCredito = ValorAplicableCredito;
		this.ValorRealizacion = ValorRealizacion;
		this.NumeroPiezas = NumeroPiezas;
		this.DescuentoSuelda = DescuentoSuelda;
		this.valorOro = valorOro;
		this.valorAvaluo = valorAvaluo;
	}
}