package com.relative.QuskyOro.ObjetosNegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ObjetoAOrdenar implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Item")
	private java.lang.String item;
	@org.kie.api.definition.type.Label(value = "Valor")
	private java.lang.Double valor;

	public ObjetoAOrdenar() {
	}

	public java.lang.String getItem() {
		return this.item;
	}

	public void setItem(java.lang.String item) {
		this.item = item;
	}

	public java.lang.Double getValor() {
		return this.valor;
	}

	public void setValor(java.lang.Double valor) {
		this.valor = valor;
	}

	public ObjetoAOrdenar(java.lang.String item, java.lang.Double valor) {
		this.item = item;
		this.valor = valor;
	}

}