package com.relative.QuskyOro.ObjetosNegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class OfertasSimuladas implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Opcion")
	private java.util.List<com.relative.QuskyOro.ObjetosNegocio.OpcionSimulada> opcion;

	public OfertasSimuladas() {
	}

	public java.util.List<com.relative.QuskyOro.ObjetosNegocio.OpcionSimulada> getOpcion() {
		return this.opcion;
	}

	public void setOpcion(
			java.util.List<com.relative.QuskyOro.ObjetosNegocio.OpcionSimulada> opcion) {
		this.opcion = opcion;
	}

	public OfertasSimuladas(
			java.util.List<com.relative.QuskyOro.ObjetosNegocio.OpcionSimulada> opcion) {
		this.opcion = opcion;
	}

}