package com.relative.QuskyOro.ObjetosNegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ParametrosRiesgo implements java.io.Serializable {

	static final long serialVersionUID = 1L;
	@org.kie.api.definition.type.Label("PerfilRiesgo")
	private String PerfilRiesgo;
	@org.kie.api.definition.type.Label("OrigenOperacion")
	private String OrigenOperacion;
	@org.kie.api.definition.type.Label("RiesgoTotal")
	private String RiesgoTotal;
	@org.kie.api.definition.type.Label("FechaNacimiento")
	private String FechaNacimiento;
	@org.kie.api.definition.type.Label("PerfilPreferencia")
	private String PerfilPreferencia;
	@org.kie.api.definition.type.Label("AgenciaOriginacion")
	private String AgenciaOriginacion;
	@org.kie.api.definition.type.Label("IdentificacionCliente")
	private String IdentificacionCliente;

	@org.kie.api.definition.type.Label("CalificacionMupi")
	private java.lang.String calificacionMupi;

	@org.kie.api.definition.type.Label(value = "CoberturaExcepcionada")
	private java.lang.Integer coberturaExcepcionada;

	public ParametrosRiesgo() {
	}

	// Getter Methods

	public String getPerfilRiesgo() {
		return PerfilRiesgo;
	}

	public String getOrigenOperacion() {
		return OrigenOperacion;
	}

	public String getRiesgoTotal() {
		return RiesgoTotal;
	}

	public String getFechaNacimiento() {
		return FechaNacimiento;
	}

	public String getPerfilPreferencia() {
		return PerfilPreferencia;
	}

	public String getAgenciaOriginacion() {
		return AgenciaOriginacion;
	}

	public String getIdentificacionCliente() {
		return IdentificacionCliente;
	}

	// Setter Methods

	public void setPerfilRiesgo(String PerfilRiesgo) {
		this.PerfilRiesgo = PerfilRiesgo;
	}

	public void setOrigenOperacion(String OrigenOperacion) {
		this.OrigenOperacion = OrigenOperacion;
	}

	public void setRiesgoTotal(String RiesgoTotal) {
		this.RiesgoTotal = RiesgoTotal;
	}

	public void setFechaNacimiento(String FechaNacimiento) {
		this.FechaNacimiento = FechaNacimiento;
	}

	public void setPerfilPreferencia(String PerfilPreferencia) {
		this.PerfilPreferencia = PerfilPreferencia;
	}

	public void setAgenciaOriginacion(String AgenciaOriginacion) {
		this.AgenciaOriginacion = AgenciaOriginacion;
	}

	public void setIdentificacionCliente(String IdentificacionCliente) {
		this.IdentificacionCliente = IdentificacionCliente;
	}

	public java.lang.String getCalificacionMupi() {
		return this.calificacionMupi;
	}

	public void setCalificacionMupi(java.lang.String calificacionMupi) {
		this.calificacionMupi = calificacionMupi;
	}

	public java.lang.Integer getCoberturaExcepcionada() {
		return this.coberturaExcepcionada;
	}

	public void setCoberturaExcepcionada(java.lang.Integer coberturaExcepcionada) {
		this.coberturaExcepcionada = coberturaExcepcionada;
	}

	public ParametrosRiesgo(java.lang.String PerfilRiesgo,
			java.lang.String OrigenOperacion, java.lang.String RiesgoTotal,
			java.lang.String FechaNacimiento,
			java.lang.String PerfilPreferencia,
			java.lang.String AgenciaOriginacion,
			java.lang.String IdentificacionCliente,
			java.lang.String calificacionMupi,
			java.lang.Integer coberturaExcepcionada) {
		this.PerfilRiesgo = PerfilRiesgo;
		this.OrigenOperacion = OrigenOperacion;
		this.RiesgoTotal = RiesgoTotal;
		this.FechaNacimiento = FechaNacimiento;
		this.PerfilPreferencia = PerfilPreferencia;
		this.AgenciaOriginacion = AgenciaOriginacion;
		this.IdentificacionCliente = IdentificacionCliente;
		this.calificacionMupi = calificacionMupi;
		this.coberturaExcepcionada = coberturaExcepcionada;
	}
}