package com.relative.QuskyOro.ObjetosNegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SimularResponseSimulation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "SimularResultSimulation")
	private com.relative.QuskyOro.ObjetosNegocio.SimularResultSimulation simularResultSimulation;

	public SimularResponseSimulation() {
	}

	public com.relative.QuskyOro.ObjetosNegocio.SimularResultSimulation getSimularResultSimulation() {
		return this.simularResultSimulation;
	}

	public void setSimularResultSimulation(
			com.relative.QuskyOro.ObjetosNegocio.SimularResultSimulation simularResultSimulation) {
		this.simularResultSimulation = simularResultSimulation;
	}

	public SimularResponseSimulation(
			com.relative.QuskyOro.ObjetosNegocio.SimularResultSimulation simularResultSimulation) {
		this.simularResultSimulation = simularResultSimulation;
	}

}