package com.relative.QuskyOro.ObjetosNegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SimularResultGarantias implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "XmlGarantias")
	private com.relative.QuskyOro.ObjetosNegocio.XmlGarantias xmlGarantias;
	@org.kie.api.definition.type.Label(value = "CodigoError")
	private java.lang.String codigoError;
	@org.kie.api.definition.type.Label(value = "Mensaje")
	private java.lang.String mensaje;
	@org.kie.api.definition.type.Label(value = "NumeroOperacionMadre")
	private java.lang.String numeroOperacionMadre;

	public SimularResultGarantias() {
	}

	public com.relative.QuskyOro.ObjetosNegocio.XmlGarantias getXmlGarantias() {
		return this.xmlGarantias;
	}

	public void setXmlGarantias(
			com.relative.QuskyOro.ObjetosNegocio.XmlGarantias xmlGarantias) {
		this.xmlGarantias = xmlGarantias;
	}

	public java.lang.String getCodigoError() {
		return this.codigoError;
	}

	public void setCodigoError(java.lang.String codigoError) {
		this.codigoError = codigoError;
	}

	public java.lang.String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(java.lang.String mensaje) {
		this.mensaje = mensaje;
	}

	public java.lang.String getNumeroOperacionMadre() {
		return this.numeroOperacionMadre;
	}

	public void setNumeroOperacionMadre(java.lang.String numeroOperacionMadre) {
		this.numeroOperacionMadre = numeroOperacionMadre;
	}

	public SimularResultGarantias(
			com.relative.QuskyOro.ObjetosNegocio.XmlGarantias xmlGarantias,
			java.lang.String codigoError, java.lang.String mensaje,
			java.lang.String numeroOperacionMadre) {
		this.xmlGarantias = xmlGarantias;
		this.codigoError = codigoError;
		this.mensaje = mensaje;
		this.numeroOperacionMadre = numeroOperacionMadre;
	}

}