package com.relative.QuskyOro.ObjetosNegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SimularResultSimulation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "XmlOfertasSimuladas")
	private com.relative.QuskyOro.ObjetosNegocio.XmlOfertasSimuladas xmlOfertasSimuladas;
	@org.kie.api.definition.type.Label(value = "CodigoError")
	private java.lang.String codigoError;
	@org.kie.api.definition.type.Label(value = "Mensaje")
	private java.lang.String mensaje;
	@org.kie.api.definition.type.Label(value = "NumeroOperacionMadre")
	private java.lang.String numeroOperacionMadre;

	public SimularResultSimulation() {
	}

	public com.relative.QuskyOro.ObjetosNegocio.XmlOfertasSimuladas getXmlOfertasSimuladas() {
		return this.xmlOfertasSimuladas;
	}

	public void setXmlOfertasSimuladas(
			com.relative.QuskyOro.ObjetosNegocio.XmlOfertasSimuladas xmlOfertasSimuladas) {
		this.xmlOfertasSimuladas = xmlOfertasSimuladas;
	}

	public java.lang.String getCodigoError() {
		return this.codigoError;
	}

	public void setCodigoError(java.lang.String codigoError) {
		this.codigoError = codigoError;
	}

	public java.lang.String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(java.lang.String mensaje) {
		this.mensaje = mensaje;
	}

	public java.lang.String getNumeroOperacionMadre() {
		return this.numeroOperacionMadre;
	}

	public void setNumeroOperacionMadre(java.lang.String numeroOperacionMadre) {
		this.numeroOperacionMadre = numeroOperacionMadre;
	}

	public SimularResultSimulation(
			com.relative.QuskyOro.ObjetosNegocio.XmlOfertasSimuladas xmlOfertasSimuladas,
			java.lang.String codigoError, java.lang.String mensaje,
			java.lang.String numeroOperacionMadre) {
		this.xmlOfertasSimuladas = xmlOfertasSimuladas;
		this.codigoError = codigoError;
		this.mensaje = mensaje;
		this.numeroOperacionMadre = numeroOperacionMadre;
	}

}