package com.relative.QuskyOro.ObjetosNegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class XmlGarantias implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Garantias")
	private com.relative.QuskyOro.ObjetosNegocio.Garantias Garantias;

	public XmlGarantias() {
	}

	public com.relative.QuskyOro.ObjetosNegocio.Garantias getGarantias() {
		return this.Garantias;
	}

	public void setGarantias(
			com.relative.QuskyOro.ObjetosNegocio.Garantias garantias) {
		this.Garantias = garantias;
	}

	public XmlGarantias(
			com.relative.QuskyOro.ObjetosNegocio.Garantias garantias) {
		this.Garantias = garantias;
	}

}