package com.relative.QuskyOro.ObjetosNegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Description("Este objeto guarda el conjunto de objetos VariablesInternas del xml de entrada")
public class XmlVariablesInternas implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("VariablesInternas")
	private com.relative.QuskyOro.ObjetosNegocio.VariablesInternas variablesInternas;

	public XmlVariablesInternas() {
	}

	public com.relative.QuskyOro.ObjetosNegocio.VariablesInternas getVariablesInternas() {
		return this.variablesInternas;
	}

	public void setVariablesInternas(
			com.relative.QuskyOro.ObjetosNegocio.VariablesInternas variablesInternas) {
		this.variablesInternas = variablesInternas;
	}

	public XmlVariablesInternas(
			com.relative.QuskyOro.ObjetosNegocio.VariablesInternas variablesInternas) {
		this.variablesInternas = variablesInternas;
	}

}