package com.relative.QuskiOro.ObjetosNegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CalculadoraQuskiResultSimulation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "SimularResponseSimulation")
	private com.relative.QuskiOro.ObjetosNegocio.SimularResponseSimulation simularResponseSimulation;

	public CalculadoraQuskiResultSimulation() {
	}

	public com.relative.QuskiOro.ObjetosNegocio.SimularResponseSimulation getSimularResponseSimulation() {
		return this.simularResponseSimulation;
	}

	public void setSimularResponseSimulation(
			com.relative.QuskiOro.ObjetosNegocio.SimularResponseSimulation simularResponseSimulation) {
		this.simularResponseSimulation = simularResponseSimulation;
	}

	public CalculadoraQuskiResultSimulation(
			com.relative.QuskiOro.ObjetosNegocio.SimularResponseSimulation simularResponseSimulation) {
		this.simularResponseSimulation = simularResponseSimulation;
	}

}