package com.relative.QuskiOro.ObjetosNegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DescuentosOperacion implements java.io.Serializable {

	static final long serialVersionUID = 1L;
	@org.kie.api.definition.type.Label("SaldoMontoCreditoAnterior")
	private Double SaldoMontoCreditoAnterior;
	@org.kie.api.definition.type.Label("SaldoInteresCreditoAnterior")
	private Double SaldoInteresCreditoAnterior;
	@org.kie.api.definition.type.Label("MoraCreditoAnterior")
	private Double MoraCreditoAnterior;
	@org.kie.api.definition.type.Label("CobranzaCreditoAnterior")
	private Double CobranzaCreditoAnterior;
	@org.kie.api.definition.type.Label("TipoCartera")
	private String TipoCartera;
	@org.kie.api.definition.type.Label("MontoFinanciadoCreditoAnterior")
	private Double MontoFinanciadoCreditoAnterior;
	@org.kie.api.definition.type.Label("PlazoCreditoAnterior")
	private Integer PlazoCreditoAnterior;
	@org.kie.api.definition.type.Label("TipoCreditoAnterior")
	private String TipoCreditoAnterior;
	@org.kie.api.definition.type.Label("EstadoCreditoAnterior")
	private String EstadoCreditoAnterior;
	@org.kie.api.definition.type.Label("FechaEfectivaCreditoAnterior")
	private String FechaEfectivaCreditoAnterior;
	@org.kie.api.definition.type.Label("FechaVencimientoCreditoAnterior")
	private String FechaVencimientoCreditoAnterior;
	@org.kie.api.definition.type.Label("MontoSolicitadoCliente")
	private Double MontoSolicitadoCliente;
	@org.kie.api.definition.type.Label("NumeroOperacionMadre")
	private String NumeroOperacionMadre;
	@org.kie.api.definition.type.Label("NumeroOperacionRenovar")
	private String NumeroOperacionRenovar;
	@org.kie.api.definition.type.Label("REFERENCIA_ADICIONAL")
	private String REFERENCIA_ADICIONAL;
	@org.kie.api.definition.type.Label("OperacionPropia")
	private String OperacionPropia;

	@org.kie.api.definition.type.Label("CustodiaDevengadaCreditoAnterior")
	private java.lang.Double custodiaDevengadaCreditoAnterior;

	public DescuentosOperacion() {
	}

	// Getter Methods

	public Double getSaldoMontoCreditoAnterior() {
		return SaldoMontoCreditoAnterior;
	}

	public Double getSaldoInteresCreditoAnterior() {
		return SaldoInteresCreditoAnterior;
	}

	public Double getMoraCreditoAnterior() {
		return MoraCreditoAnterior;
	}

	public Double getCobranzaCreditoAnterior() {
		return CobranzaCreditoAnterior;
	}

	public String getTipoCartera() {
		return TipoCartera;
	}

	public Double getMontoFinanciadoCreditoAnterior() {
		return MontoFinanciadoCreditoAnterior;
	}

	public Integer getPlazoCreditoAnterior() {
		return PlazoCreditoAnterior;
	}

	public String getTipoCreditoAnterior() {
		return TipoCreditoAnterior;
	}

	public String getEstadoCreditoAnterior() {
		return EstadoCreditoAnterior;
	}

	public String getFechaEfectivaCreditoAnterior() {
		return FechaEfectivaCreditoAnterior;
	}

	public String getFechaVencimientoCreditoAnterior() {
		return FechaVencimientoCreditoAnterior;
	}

	public Double getMontoSolicitadoCliente() {
		return MontoSolicitadoCliente;
	}

	public String getREFERENCIA_ADICIONAL() {
		return REFERENCIA_ADICIONAL;
	}

	public String getOperacionPropia() {
		return OperacionPropia;
	}

	// Setter Methods

	public void setSaldoMontoCreditoAnterior(Double SaldoMontoCreditoAnterior) {
		this.SaldoMontoCreditoAnterior = SaldoMontoCreditoAnterior;
	}

	public void setSaldoInteresCreditoAnterior(
			Double SaldoInteresCreditoAnterior) {
		this.SaldoInteresCreditoAnterior = SaldoInteresCreditoAnterior;
	}

	public void setMoraCreditoAnterior(Double MoraCreditoAnterior) {
		this.MoraCreditoAnterior = MoraCreditoAnterior;
	}

	public void setCobranzaCreditoAnterior(Double CobranzaCreditoAnterior) {
		this.CobranzaCreditoAnterior = CobranzaCreditoAnterior;
	}

	public void setTipoCartera(String TipoCartera) {
		this.TipoCartera = TipoCartera;
	}

	public void setMontoFinanciadoCreditoAnterior(
			Double MontoFinanciadoCreditoAnterior) {
		this.MontoFinanciadoCreditoAnterior = MontoFinanciadoCreditoAnterior;
	}

	public void setPlazoCreditoAnterior(Integer PlazoCreditoAnterior) {
		this.PlazoCreditoAnterior = PlazoCreditoAnterior;
	}

	public void setTipoCreditoAnterior(String TipoCreditoAnterior) {
		this.TipoCreditoAnterior = TipoCreditoAnterior;
	}

	public void setEstadoCreditoAnterior(String EstadoCreditoAnterior) {
		this.EstadoCreditoAnterior = EstadoCreditoAnterior;
	}

	public void setFechaEfectivaCreditoAnterior(
			String FechaEfectivaCreditoAnterior) {
		this.FechaEfectivaCreditoAnterior = FechaEfectivaCreditoAnterior;
	}

	public void setFechaVencimientoCreditoAnterior(
			String FechaVencimientoCreditoAnterior) {
		this.FechaVencimientoCreditoAnterior = FechaVencimientoCreditoAnterior;
	}

	public void setMontoSolicitadoCliente(Double MontoSolicitadoCliente) {
		this.MontoSolicitadoCliente = MontoSolicitadoCliente;
	}

	public void setREFERENCIA_ADICIONAL(String REFERENCIA_ADICIONAL) {
		this.REFERENCIA_ADICIONAL = REFERENCIA_ADICIONAL;
	}

	public void setOperacionPropia(String OperacionPropia) {
		this.OperacionPropia = OperacionPropia;
	}

	public java.lang.Double getCustodiaDevengadaCreditoAnterior() {
		return this.custodiaDevengadaCreditoAnterior;
	}

	public void setCustodiaDevengadaCreditoAnterior(
			java.lang.Double custodiaDevengadaCreditoAnterior) {
		this.custodiaDevengadaCreditoAnterior = custodiaDevengadaCreditoAnterior;
	}

	public java.lang.String getNumeroOperacionMadre() {
		return this.NumeroOperacionMadre;
	}

	public void setNumeroOperacionMadre(java.lang.String NumeroOperacionMadre) {
		this.NumeroOperacionMadre = NumeroOperacionMadre;
	}

	public java.lang.String getNumeroOperacionRenovar() {
		return this.NumeroOperacionRenovar;
	}

	public void setNumeroOperacionRenovar(
			java.lang.String NumeroOperacionRenovar) {
		this.NumeroOperacionRenovar = NumeroOperacionRenovar;
	}

	public DescuentosOperacion(java.lang.Double SaldoMontoCreditoAnterior,
			java.lang.Double SaldoInteresCreditoAnterior,
			java.lang.Double MoraCreditoAnterior,
			java.lang.Double CobranzaCreditoAnterior,
			java.lang.String TipoCartera,
			java.lang.Double MontoFinanciadoCreditoAnterior,
			java.lang.Integer PlazoCreditoAnterior,
			java.lang.String TipoCreditoAnterior,
			java.lang.String EstadoCreditoAnterior,
			java.lang.String FechaEfectivaCreditoAnterior,
			java.lang.String FechaVencimientoCreditoAnterior,
			java.lang.Double MontoSolicitadoCliente,
			java.lang.String NumeroOperacionMadre,
			java.lang.String NumeroOperacionRenovar,
			java.lang.String REFERENCIA_ADICIONAL,
			java.lang.String OperacionPropia,
			java.lang.Double custodiaDevengadaCreditoAnterior) {
		this.SaldoMontoCreditoAnterior = SaldoMontoCreditoAnterior;
		this.SaldoInteresCreditoAnterior = SaldoInteresCreditoAnterior;
		this.MoraCreditoAnterior = MoraCreditoAnterior;
		this.CobranzaCreditoAnterior = CobranzaCreditoAnterior;
		this.TipoCartera = TipoCartera;
		this.MontoFinanciadoCreditoAnterior = MontoFinanciadoCreditoAnterior;
		this.PlazoCreditoAnterior = PlazoCreditoAnterior;
		this.TipoCreditoAnterior = TipoCreditoAnterior;
		this.EstadoCreditoAnterior = EstadoCreditoAnterior;
		this.FechaEfectivaCreditoAnterior = FechaEfectivaCreditoAnterior;
		this.FechaVencimientoCreditoAnterior = FechaVencimientoCreditoAnterior;
		this.MontoSolicitadoCliente = MontoSolicitadoCliente;
		this.NumeroOperacionMadre = NumeroOperacionMadre;
		this.NumeroOperacionRenovar = NumeroOperacionRenovar;
		this.REFERENCIA_ADICIONAL = REFERENCIA_ADICIONAL;
		this.OperacionPropia = OperacionPropia;
		this.custodiaDevengadaCreditoAnterior = custodiaDevengadaCreditoAnterior;
	}
}