package com.relative.QuskiOro.ObjetosNegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SimularResponseGarantias implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "SimularResultGarantias")
	private com.relative.QuskiOro.ObjetosNegocio.SimularResultGarantias simularResultGarantias;

	public SimularResponseGarantias() {
	}

	public com.relative.QuskiOro.ObjetosNegocio.SimularResultGarantias getSimularResultGarantias() {
		return this.simularResultGarantias;
	}

	public void setSimularResultGarantias(
			com.relative.QuskiOro.ObjetosNegocio.SimularResultGarantias simularResultGarantias) {
		this.simularResultGarantias = simularResultGarantias;
	}

	public SimularResponseGarantias(
			com.relative.QuskiOro.ObjetosNegocio.SimularResultGarantias simularResultGarantias) {
		this.simularResultGarantias = simularResultGarantias;
	}

}