package com.relative.QuskiOro.ObjetosNegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class VariablesInternas implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("TipoCliente")
	private java.lang.String TipoCliente;

	@org.kie.api.definition.type.Label("MoraPromedio")
	private java.lang.Integer moraPromedio;

	@org.kie.api.definition.type.Label("MoraMaximo")
	private java.lang.Integer moraMaximo;

	@org.kie.api.definition.type.Label("CantidadCreditos")
	private java.lang.Integer cantidadCreditos;

	@org.kie.api.definition.type.Label("CantidadPagos")
	private java.lang.Integer cantidadPagos;

	@org.kie.api.definition.type.Label("ScoreDeudor")
	private java.lang.Integer scoreDeudor;

	@org.kie.api.definition.type.Label("ValorOnzaTroy")
	private java.lang.Double valorOnzaTroy;

	@org.kie.api.definition.type.Label("VinculadosConsepMupi")
	private java.lang.String vinculadosConsepMupi;

	@org.kie.api.definition.type.Label("ImpagoQuski")
	private java.lang.String impagoQuski;

	@org.kie.api.definition.type.Label("ClienteBloqueado")
	private java.lang.String clienteBloqueado;

	@org.kie.api.definition.type.Label("VinculadoQuski")
	private java.lang.String vinculadoQuski;

	@org.kie.api.definition.type.Label("TotalCreditos")
	private java.lang.Integer totalCreditos;

	@org.kie.api.definition.type.Label("CarteraCliente")
	private java.lang.String carteraCliente;

	@org.kie.api.definition.type.Label("Permanencia")
	private java.lang.Integer permanencia;

	@org.kie.api.definition.type.Label("RiesgoAcumulado")
	private java.lang.Double riesgoAcumulado;

	@org.kie.api.definition.type.Label("ScoreComportamiento")
	private java.lang.Integer scoreComportamiento;

	@org.kie.api.definition.type.Label("CarteraCastigada")
	private java.lang.Double carteraCastigada;

	@org.kie.api.definition.type.Label("CVencida90D")
	private java.lang.Double cVencida90D;

	@org.kie.api.definition.type.Label("TiempoCancelacion")
	private java.lang.Integer tiempoCancelacion;

	@org.kie.api.definition.type.Label(value = "TipoOperacion")
	private java.lang.String tipoOperacion;

	public VariablesInternas() {
	}

	public java.lang.String getTipoCliente() {
		return this.TipoCliente;
	}

	public void setTipoCliente(java.lang.String TipoCliente) {
		this.TipoCliente = TipoCliente;
	}

	public java.lang.Integer getMoraPromedio() {
		return this.moraPromedio;
	}

	public void setMoraPromedio(java.lang.Integer moraPromedio) {
		this.moraPromedio = moraPromedio;
	}

	public java.lang.Integer getMoraMaximo() {
		return this.moraMaximo;
	}

	public void setMoraMaximo(java.lang.Integer moraMaximo) {
		this.moraMaximo = moraMaximo;
	}

	public java.lang.Integer getCantidadCreditos() {
		return this.cantidadCreditos;
	}

	public void setCantidadCreditos(java.lang.Integer cantidadCreditos) {
		this.cantidadCreditos = cantidadCreditos;
	}

	public java.lang.Integer getCantidadPagos() {
		return this.cantidadPagos;
	}

	public void setCantidadPagos(java.lang.Integer cantidadPagos) {
		this.cantidadPagos = cantidadPagos;
	}

	public java.lang.Integer getScoreDeudor() {
		return this.scoreDeudor;
	}

	public void setScoreDeudor(java.lang.Integer scoreDeudor) {
		this.scoreDeudor = scoreDeudor;
	}

	public java.lang.Double getValorOnzaTroy() {
		return this.valorOnzaTroy;
	}

	public void setValorOnzaTroy(java.lang.Double valorOnzaTroy) {
		this.valorOnzaTroy = valorOnzaTroy;
	}

	public java.lang.String getVinculadosConsepMupi() {
		return this.vinculadosConsepMupi;
	}

	public void setVinculadosConsepMupi(java.lang.String vinculadosConsepMupi) {
		this.vinculadosConsepMupi = vinculadosConsepMupi;
	}

	public java.lang.String getImpagoQuski() {
		return this.impagoQuski;
	}

	public void setImpagoQuski(java.lang.String impagoQuski) {
		this.impagoQuski = impagoQuski;
	}

	public java.lang.String getClienteBloqueado() {
		return this.clienteBloqueado;
	}

	public void setClienteBloqueado(java.lang.String clienteBloqueado) {
		this.clienteBloqueado = clienteBloqueado;
	}

	public java.lang.String getVinculadoQuski() {
		return this.vinculadoQuski;
	}

	public void setVinculadoQuski(java.lang.String vinculadoQuski) {
		this.vinculadoQuski = vinculadoQuski;
	}

	public java.lang.Integer getTotalCreditos() {
		return this.totalCreditos;
	}

	public void setTotalCreditos(java.lang.Integer totalCreditos) {
		this.totalCreditos = totalCreditos;
	}

	public java.lang.String getCarteraCliente() {
		return this.carteraCliente;
	}

	public void setCarteraCliente(java.lang.String carteraCliente) {
		this.carteraCliente = carteraCliente;
	}

	public java.lang.Integer getPermanencia() {
		return this.permanencia;
	}

	public void setPermanencia(java.lang.Integer permanencia) {
		this.permanencia = permanencia;
	}

	public java.lang.Double getRiesgoAcumulado() {
		return this.riesgoAcumulado;
	}

	public void setRiesgoAcumulado(java.lang.Double riesgoAcumulado) {
		this.riesgoAcumulado = riesgoAcumulado;
	}

	public java.lang.Integer getScoreComportamiento() {
		return this.scoreComportamiento;
	}

	public void setScoreComportamiento(java.lang.Integer scoreComportamiento) {
		this.scoreComportamiento = scoreComportamiento;
	}

	public java.lang.Double getCarteraCastigada() {
		return this.carteraCastigada;
	}

	public void setCarteraCastigada(java.lang.Double carteraCastigada) {
		this.carteraCastigada = carteraCastigada;
	}

	public java.lang.Double getcVencida90D() {
		return this.cVencida90D;
	}

	public void setcVencida90D(java.lang.Double cVencida90D) {
		this.cVencida90D = cVencida90D;
	}

	public java.lang.Integer getTiempoCancelacion() {
		return this.tiempoCancelacion;
	}

	public void setTiempoCancelacion(java.lang.Integer tiempoCancelacion) {
		this.tiempoCancelacion = tiempoCancelacion;
	}

	public java.lang.String getTipoOperacion() {
		return this.tipoOperacion;
	}

	public void setTipoOperacion(java.lang.String tipoOperacion) {
		this.tipoOperacion = tipoOperacion;
	}

	public VariablesInternas(java.lang.String TipoCliente,
			java.lang.Integer moraPromedio, java.lang.Integer moraMaximo,
			java.lang.Integer cantidadCreditos,
			java.lang.Integer cantidadPagos, java.lang.Integer scoreDeudor,
			java.lang.Double valorOnzaTroy,
			java.lang.String vinculadosConsepMupi,
			java.lang.String impagoQuski, java.lang.String clienteBloqueado,
			java.lang.String vinculadoQuski, java.lang.Integer totalCreditos,
			java.lang.String carteraCliente, java.lang.Integer permanencia,
			java.lang.Double riesgoAcumulado,
			java.lang.Integer scoreComportamiento,
			java.lang.Double carteraCastigada, java.lang.Double cVencida90D,
			java.lang.Integer tiempoCancelacion, java.lang.String tipoOperacion) {
		this.TipoCliente = TipoCliente;
		this.moraPromedio = moraPromedio;
		this.moraMaximo = moraMaximo;
		this.cantidadCreditos = cantidadCreditos;
		this.cantidadPagos = cantidadPagos;
		this.scoreDeudor = scoreDeudor;
		this.valorOnzaTroy = valorOnzaTroy;
		this.vinculadosConsepMupi = vinculadosConsepMupi;
		this.impagoQuski = impagoQuski;
		this.clienteBloqueado = clienteBloqueado;
		this.vinculadoQuski = vinculadoQuski;
		this.totalCreditos = totalCreditos;
		this.carteraCliente = carteraCliente;
		this.permanencia = permanencia;
		this.riesgoAcumulado = riesgoAcumulado;
		this.scoreComportamiento = scoreComportamiento;
		this.carteraCastigada = carteraCastigada;
		this.cVencida90D = cVencida90D;
		this.tiempoCancelacion = tiempoCancelacion;
		this.tipoOperacion = tipoOperacion;
	}

}