package com.relative.QuskiOro.ObjetosNegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Variable implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Nombre")
	private java.lang.String nombre;
	@org.kie.api.definition.type.Label("Orden")
	private java.lang.Integer orden;
	@org.kie.api.definition.type.Label("Valor")
	private java.lang.String valor;

	@org.kie.api.definition.type.Label(value = "Codigo")
	private java.lang.String codigo;

	public Variable() {
	}

	public java.lang.String getNombre() {
		return this.nombre;
	}

	public void setNombre(java.lang.String nombre) {
		this.nombre = nombre;
	}

	public java.lang.Integer getOrden() {
		return this.orden;
	}

	public void setOrden(java.lang.Integer orden) {
		this.orden = orden;
	}

	public java.lang.String getValor() {
		return this.valor;
	}

	public void setValor(java.lang.String valor) {
		this.valor = valor;
	}

	public Variable(java.lang.Integer orden, java.lang.String nombre,
			java.lang.String valor) {
		this.nombre = nombre;
		this.orden = orden;
		this.valor = valor;
	}

	public java.lang.String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(java.lang.String codigo) {
		this.codigo = codigo;
	}

	public Variable(java.lang.String nombre, java.lang.Integer orden,
			java.lang.String valor, java.lang.String codigo) {
		this.nombre = nombre;
		this.orden = orden;
		this.valor = valor;
		this.codigo = codigo;
	}

}