package com.relative.QuskiOro.ObjetosNegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class VariablesNegocio implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("TotalGarantia")
	private java.lang.Double totalGarantia;
	@org.kie.api.definition.type.Label("TotalPeso")
	private java.lang.Double totalPeso;

	@org.kie.api.definition.type.Label("PrecioGramo")
	private java.lang.Double precioGramo;

	@org.kie.api.definition.type.Label("Detener")
	private java.lang.Boolean detener;

	@org.kie.api.definition.type.Label("DetenerColateral")
	private java.lang.Boolean detenerColateral;

	@org.kie.api.definition.type.Label("DetenerColateralAdicional")
	private java.lang.Boolean detenerColateralAdicional;

	@org.kie.api.definition.type.Label("CodigoPoliticaBloqueo")
	private java.lang.String codigoPoliticaBloqueo;

	@org.kie.api.definition.type.Label("Politica")
	private java.lang.String politica;

	@org.kie.api.definition.type.Label("CodigoPolitica")
	private java.util.List<java.lang.String> codigoPolitica;

	@org.kie.api.definition.type.Label("Total Precio Oro")
	private java.lang.Double totalPrecioOro;

	@org.kie.api.definition.type.Label("CodigoError")
	private java.lang.String codigoError;

	@org.kie.api.definition.type.Label("Mensaje")
	private java.lang.String mensaje;

	@org.kie.api.definition.type.Label("TotalServiciosCapitalizados")
	private java.lang.Double totalServiciosCapitalizados;

	@org.kie.api.definition.type.Label("TotalServiciosDiferidos")
	private java.lang.Double totalServiciosDiferidos;

	@org.kie.api.definition.type.Label("TipoOperacion")
	private java.lang.String tipoOperacion;

	@org.kie.api.definition.type.Label("TotalGarantiaOperacionActual")
	private java.lang.Double totalGarantiaOperacionActual;

	@org.kie.api.definition.type.Label("DetenerCalculoMontoNovacion")
	private java.lang.Boolean detenerCalculoMontoNovacion;

	@org.kie.api.definition.type.Label("MontoFinanciadoNovacionesAnterior")
	private java.lang.Double montoFinanciadoNovacionesAnterior;

	@org.kie.api.definition.type.Label("MontoFinanciadoNovaciones")
	private java.lang.Double montoFinanciadoNovaciones;

	@org.kie.api.definition.type.Label("RecalcularColateralMontoNovacion")
	private java.lang.Boolean recalcularColateralMontoNovacion;

	@org.kie.api.definition.type.Label("MontoSolicitadoCliente")
	private java.lang.Double montoSolicitadoCliente;

	@org.kie.api.definition.type.Label("CodigoMensajeError")
	private java.lang.String codigoMensajeError;

	@org.kie.api.definition.type.Label("MensajeError")
	private java.lang.String mensajeError;

	@org.kie.api.definition.type.Label("CodigoMensajeErrorConstante")
	private java.lang.String codigoMensajeErrorConstante;

	@org.kie.api.definition.type.Label("AbonoCapital")
	private java.lang.Double abonoCapital;

	@org.kie.api.definition.type.Label("TotalServiciosDesembolso")
	private java.lang.Double totalServiciosDesembolso;

	@org.kie.api.definition.type.Label("ValidacionNovacionesA")
	private java.lang.Double validacionNovacionesA;

	@org.kie.api.definition.type.Label("ValidacionNovacionesB")
	private java.lang.Double validacionNovacionesB;

	@org.kie.api.definition.type.Label("TipoRenovacion")
	private java.lang.String tipoRenovacion;

	@org.kie.api.definition.type.Label("Retanqueo")
	private java.lang.String retanqueo;

	@org.kie.api.definition.type.Label(value = "TipoCreditoAnterior")
	private java.lang.String tipoCreditoAnterior;

	public VariablesNegocio() {
	}

	public java.lang.Double getTotalGarantia() {
		return this.totalGarantia;
	}

	public void setTotalGarantia(java.lang.Double totalGarantia) {
		this.totalGarantia = totalGarantia;
	}

	public java.lang.Double getTotalPeso() {
		return this.totalPeso;
	}

	public void setTotalPeso(java.lang.Double totalPeso) {
		this.totalPeso = totalPeso;
	}

	public java.lang.Double getPrecioGramo() {
		return this.precioGramo;
	}

	public void setPrecioGramo(java.lang.Double precioGramo) {
		this.precioGramo = precioGramo;
	}

	public java.lang.Boolean getDetener() {
		return this.detener;
	}

	public void setDetener(java.lang.Boolean detener) {
		this.detener = detener;
	}

	public java.lang.Boolean getDetenerColateral() {
		return this.detenerColateral;
	}

	public void setDetenerColateral(java.lang.Boolean detenerColateral) {
		this.detenerColateral = detenerColateral;
	}

	public java.lang.Boolean getDetenerColateralAdicional() {
		return this.detenerColateralAdicional;
	}

	public void setDetenerColateralAdicional(
			java.lang.Boolean detenerColateralAdicional) {
		this.detenerColateralAdicional = detenerColateralAdicional;
	}

	public java.lang.String getCodigoPoliticaBloqueo() {
		return this.codigoPoliticaBloqueo;
	}

	public void setCodigoPoliticaBloqueo(java.lang.String codigoPoliticaBloqueo) {
		this.codigoPoliticaBloqueo = codigoPoliticaBloqueo;
	}

	public java.lang.String getPolitica() {
		return this.politica;
	}

	public void setPolitica(java.lang.String politica) {
		this.politica = politica;
	}

	public java.util.List<java.lang.String> getCodigoPolitica() {
		return this.codigoPolitica;
	}

	public void setCodigoPolitica(
			java.util.List<java.lang.String> codigoPolitica) {
		this.codigoPolitica = codigoPolitica;
	}

	public java.lang.Double getTotalPrecioOro() {
		return this.totalPrecioOro;
	}

	public void setTotalPrecioOro(java.lang.Double totalPrecioOro) {
		this.totalPrecioOro = totalPrecioOro;
	}

	public java.lang.String getCodigoError() {
		return this.codigoError;
	}

	public void setCodigoError(java.lang.String codigoError) {
		this.codigoError = codigoError;
	}

	public java.lang.String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(java.lang.String mensaje) {
		this.mensaje = mensaje;
	}

	public java.lang.Double getTotalServiciosCapitalizados() {
		return this.totalServiciosCapitalizados;
	}

	public void setTotalServiciosCapitalizados(
			java.lang.Double totalServiciosCapitalizados) {
		this.totalServiciosCapitalizados = totalServiciosCapitalizados;
	}

	public java.lang.Double getTotalServiciosDiferidos() {
		return this.totalServiciosDiferidos;
	}

	public void setTotalServiciosDiferidos(
			java.lang.Double totalServiciosDiferidos) {
		this.totalServiciosDiferidos = totalServiciosDiferidos;
	}

	public java.lang.String getTipoOperacion() {
		return this.tipoOperacion;
	}

	public void setTipoOperacion(java.lang.String tipoOperacion) {
		this.tipoOperacion = tipoOperacion;
	}

	public java.lang.Double getTotalGarantiaOperacionActual() {
		return this.totalGarantiaOperacionActual;
	}

	public void setTotalGarantiaOperacionActual(
			java.lang.Double totalGarantiaOperacionActual) {
		this.totalGarantiaOperacionActual = totalGarantiaOperacionActual;
	}

	public java.lang.Boolean getDetenerCalculoMontoNovacion() {
		return this.detenerCalculoMontoNovacion;
	}

	public void setDetenerCalculoMontoNovacion(
			java.lang.Boolean detenerCalculoMontoNovacion) {
		this.detenerCalculoMontoNovacion = detenerCalculoMontoNovacion;
	}

	public java.lang.Double getMontoFinanciadoNovacionesAnterior() {
		return this.montoFinanciadoNovacionesAnterior;
	}

	public void setMontoFinanciadoNovacionesAnterior(
			java.lang.Double montoFinanciadoNovacionesAnterior) {
		this.montoFinanciadoNovacionesAnterior = montoFinanciadoNovacionesAnterior;
	}

	public java.lang.Double getMontoFinanciadoNovaciones() {
		return this.montoFinanciadoNovaciones;
	}

	public void setMontoFinanciadoNovaciones(
			java.lang.Double montoFinanciadoNovaciones) {
		this.montoFinanciadoNovaciones = montoFinanciadoNovaciones;
	}

	public java.lang.Boolean getRecalcularColateralMontoNovacion() {
		return this.recalcularColateralMontoNovacion;
	}

	public void setRecalcularColateralMontoNovacion(
			java.lang.Boolean recalcularColateralMontoNovacion) {
		this.recalcularColateralMontoNovacion = recalcularColateralMontoNovacion;
	}

	public java.lang.Double getMontoSolicitadoCliente() {
		return this.montoSolicitadoCliente;
	}

	public void setMontoSolicitadoCliente(
			java.lang.Double montoSolicitadoCliente) {
		this.montoSolicitadoCliente = montoSolicitadoCliente;
	}

	public java.lang.String getCodigoMensajeError() {
		return this.codigoMensajeError;
	}

	public void setCodigoMensajeError(java.lang.String codigoMensajeError) {
		this.codigoMensajeError = codigoMensajeError;
	}

	public java.lang.String getMensajeError() {
		return this.mensajeError;
	}

	public void setMensajeError(java.lang.String mensajeError) {
		this.mensajeError = mensajeError;
	}

	public java.lang.String getCodigoMensajeErrorConstante() {
		return this.codigoMensajeErrorConstante;
	}

	public void setCodigoMensajeErrorConstante(
			java.lang.String codigoMensajeErrorConstante) {
		this.codigoMensajeErrorConstante = codigoMensajeErrorConstante;
	}

	public java.lang.Double getAbonoCapital() {
		return this.abonoCapital;
	}

	public void setAbonoCapital(java.lang.Double abonoCapital) {
		this.abonoCapital = abonoCapital;
	}

	public java.lang.Double getTotalServiciosDesembolso() {
		return this.totalServiciosDesembolso;
	}

	public void setTotalServiciosDesembolso(
			java.lang.Double totalServiciosDesembolso) {
		this.totalServiciosDesembolso = totalServiciosDesembolso;
	}

	public java.lang.Double getValidacionNovacionesA() {
		return this.validacionNovacionesA;
	}

	public void setValidacionNovacionesA(java.lang.Double validacionNovacionesA) {
		this.validacionNovacionesA = validacionNovacionesA;
	}

	public java.lang.Double getValidacionNovacionesB() {
		return this.validacionNovacionesB;
	}

	public void setValidacionNovacionesB(java.lang.Double validacionNovacionesB) {
		this.validacionNovacionesB = validacionNovacionesB;
	}

	public java.lang.String getTipoRenovacion() {
		return this.tipoRenovacion;
	}

	public void setTipoRenovacion(java.lang.String tipoRenovacion) {
		this.tipoRenovacion = tipoRenovacion;
	}

	public java.lang.String getRetanqueo() {
		return this.retanqueo;
	}

	public void setRetanqueo(java.lang.String retanqueo) {
		this.retanqueo = retanqueo;
	}

	public java.lang.String getTipoCreditoAnterior() {
		return this.tipoCreditoAnterior;
	}

	public void setTipoCreditoAnterior(java.lang.String tipoCreditoAnterior) {
		this.tipoCreditoAnterior = tipoCreditoAnterior;
	}

	public VariablesNegocio(java.lang.Double totalGarantia,
			java.lang.Double totalPeso, java.lang.Double precioGramo,
			java.lang.Boolean detener, java.lang.Boolean detenerColateral,
			java.lang.Boolean detenerColateralAdicional,
			java.lang.String codigoPoliticaBloqueo, java.lang.String politica,
			java.util.List<java.lang.String> codigoPolitica,
			java.lang.Double totalPrecioOro, java.lang.String codigoError,
			java.lang.String mensaje,
			java.lang.Double totalServiciosCapitalizados,
			java.lang.Double totalServiciosDiferidos,
			java.lang.String tipoOperacion,
			java.lang.Double totalGarantiaOperacionActual,
			java.lang.Boolean detenerCalculoMontoNovacion,
			java.lang.Double montoFinanciadoNovacionesAnterior,
			java.lang.Double montoFinanciadoNovaciones,
			java.lang.Boolean recalcularColateralMontoNovacion,
			java.lang.Double montoSolicitadoCliente,
			java.lang.String codigoMensajeError, java.lang.String mensajeError,
			java.lang.String codigoMensajeErrorConstante,
			java.lang.Double abonoCapital,
			java.lang.Double totalServiciosDesembolso,
			java.lang.Double validacionNovacionesA,
			java.lang.Double validacionNovacionesB,
			java.lang.String tipoRenovacion, java.lang.String retanqueo,
			java.lang.String tipoCreditoAnterior) {
		this.totalGarantia = totalGarantia;
		this.totalPeso = totalPeso;
		this.precioGramo = precioGramo;
		this.detener = detener;
		this.detenerColateral = detenerColateral;
		this.detenerColateralAdicional = detenerColateralAdicional;
		this.codigoPoliticaBloqueo = codigoPoliticaBloqueo;
		this.politica = politica;
		this.codigoPolitica = codigoPolitica;
		this.totalPrecioOro = totalPrecioOro;
		this.codigoError = codigoError;
		this.mensaje = mensaje;
		this.totalServiciosCapitalizados = totalServiciosCapitalizados;
		this.totalServiciosDiferidos = totalServiciosDiferidos;
		this.tipoOperacion = tipoOperacion;
		this.totalGarantiaOperacionActual = totalGarantiaOperacionActual;
		this.detenerCalculoMontoNovacion = detenerCalculoMontoNovacion;
		this.montoFinanciadoNovacionesAnterior = montoFinanciadoNovacionesAnterior;
		this.montoFinanciadoNovaciones = montoFinanciadoNovaciones;
		this.recalcularColateralMontoNovacion = recalcularColateralMontoNovacion;
		this.montoSolicitadoCliente = montoSolicitadoCliente;
		this.codigoMensajeError = codigoMensajeError;
		this.mensajeError = mensajeError;
		this.codigoMensajeErrorConstante = codigoMensajeErrorConstante;
		this.abonoCapital = abonoCapital;
		this.totalServiciosDesembolso = totalServiciosDesembolso;
		this.validacionNovacionesA = validacionNovacionesA;
		this.validacionNovacionesB = validacionNovacionesB;
		this.tipoRenovacion = tipoRenovacion;
		this.retanqueo = retanqueo;
		this.tipoCreditoAnterior = tipoCreditoAnterior;
	}

}