package com.relative.QuskiOro.ObjetosNegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class XmlOfertasSimuladas implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("OfertasSimuladas")
	private OfertasSimuladas ofertasSimuladas;

	public XmlOfertasSimuladas() {
	}

	public com.relative.QuskiOro.ObjetosNegocio.OfertasSimuladas getOfertasSimuladas() {
		return this.ofertasSimuladas;
	}

	public void setOfertasSimuladas(
			com.relative.QuskiOro.ObjetosNegocio.OfertasSimuladas ofertasSimuladas) {
		this.ofertasSimuladas = ofertasSimuladas;
	}

	public XmlOfertasSimuladas(
			com.relative.QuskiOro.ObjetosNegocio.OfertasSimuladas ofertasSimuladas) {
		this.ofertasSimuladas = ofertasSimuladas;
	}

}